Image.create!([
  {image_url: "http://img.gamefaqs.net/box/4/5/0/204450_front.jpg", product_id: 1},
  {image_url: "https://upload.wikimedia.org/wikipedia/en/0/07/Super_Danganronpa_2_Cover_Art.jpg", product_id: 2},
  {image_url: "http://www.hardcoregamer.com/wp-content/uploads/2015/04/dead-space.jpg", product_id: 3},
  {image_url: "http://vignette3.wikia.nocookie.net/megamitensei/images/7/71/Devil_Survivor_2_BR_Boxset.png/revision/latest?cb=20141206061113", product_id: 4},
  {image_url: "http://vignette1.wikia.nocookie.net/uncharted/images/0/02/Uncharted_3_Boxart.jpg", product_id: 5},
  {image_url: "http://mega-ps3.com/wp-content/uploads/2015/09/sin-tc3adtulo-1.png", product_id: 6},
  {image_url: "http://vignette2.wikia.nocookie.net/danganronpa/images/2/22/Danganronpaboxart.jpg", product_id: 7},
  {image_url: "http://cdn.bulbagarden.net/upload/thumb/e/eb/Alpha_Sapphire_JP_boxart.png/250px-Alpha_Sapphire_JP_boxart.png", product_id: 8},
  {image_url: "http://duuro.net/wp-content/uploads/2013/08/8007728210_703cf5fbcf_z.jpg", product_id: 1},
  {image_url: "http://gematsu.com/wp-content/uploads/2012/09/P4G_09-18.jpg", product_id: 1},
  {image_url: "http://images.nintendolife.com/games/wiiu/mario_kart_8/cover_large.jpg", product_id: 9},
  {image_url: "http://vignette3.wikia.nocookie.net/mariokart/images/6/68/Mario_(Mario_Kart_Wii).jpg", product_id: 12},
  {image_url: "http://pre08.deviantart.net/41cf/th/pre/i/2012/158/b/9/rayman_legends___cover_art_2_by_squizcat-d52mzd3.jpg", product_id: 10},
  {image_url: "http://smsouthnews.com/wp-content/uploads/2013/10/acnl.jpg", product_id: 11}
])
Order.create!([
  {user_id: 1, product_id: 2, quantity: 5, subtotal: "189.9", tax: "17.09", total: "206.99"}
])
Product.create!([
  {name: "Persona 4: Golden", price: "38.99", description: "Persona 4 takes place in a fictional Japanese countryside and is indirectly related to both Shin Megami Tensei: Persona 3 and the Persona 2 games. The player-named main protagonist is a high-school student who moved into the countryside from the city for a year. During his year-long stay, he becomes involved in investigating mysterious murders while harnessing the power of summoning Persona. The game features a weather forecast system with events happening on foggy days to replace the moon phase system implemented in the previous games. The plot of Persona 4 was inspired by the work of mystery novelists owing to its murder mystery premise. The rural setting was based on a town on the outskirts of Mount Fuji and intended as a nowhere place and is the central setting to have players sympathize with the daily life of the characters. The developers added many in-game events to prevent the game from becoming stale. During the localization, numerous alterations to names and cultural references were made to preserve the effect through translation, but some Japanese cultural references were altered or removed.", stock_info: true, supplier_id: 1, user_id: 1},
  {name: "Danganronpa 2", price: "37.98", description: "The game is from Hajime Hinata's point of view as he starts his first year at Hope's Peak Academy. As he walks into the school building he is overcome with fatigue, when he recovers he finds himself in front of a door. He has the strong urge to open it, and once he does he finds himself in a classroom full of his new classmates. They suddenly find themselves locked in the classroom and a pink bunny, Usami, appears before them, claiming herself the class' teacher. Suddenly the classroom around them falls away to reveal a paradise-like island. Usami tells them they are on a school trip and they are to befriend each other to gain hope fragments and make their hope grow. Just as they get used to the peaceful island life, Monokuma appears and takes control of the island, announcing that the students must participate in a life of mutual killing if they wish to escape.", stock_info: false, supplier_id: 2, user_id: 1},
  {name: "Dead Space", price: "29.99", description: "Dead Space is set in 2508. Earth has been through an extinction-level event, caused by rapacious and unsustainable use of resources. The remaining humans realized that the only way to gain the resources to survive would be to search new planets for resources. That's where the Concordance Extraction Corporation comes in. At a time of near-desperation, the CEC engineered the ship that would eventually save all of humanity: The USG Ishimura. The USG Ishimura was a ship designed for the new resource-gathering practice: Planetcracking. The Ishimura's job was to mine other planets for their most rare and most valuable resources to take back to Earth. Even though there have been subsequent Planetcrackers (a small fleet now exists), the Ishimura remains the iconic symbol of mankind's will to survive, even after all these decades. Thanks to Planetcracking, mankind is now thriving again, and resources are plentiful. By the time of the game, the Ishimura has performed 34 successful planetcracks, and is now in the process of beginning its 35th. However, the events that take place during this planet crack are events that threaten the very survival of mankind.", stock_info: true, supplier_id: 3, user_id: 2},
  {name: "Devil Survivor 2: Break Record", price: "50.0", description: "Devil Survivor 2 is a tactical role-playing game. Like in the previous Devil Survivor game, in combat situations, the player is free of interacting with other characters at the cost of time going by or going through free battles that do not make time continue. In fights with the computer opponent to defeat enemies and satisfy certain objectives such as helping other characters, while avoiding conditions that will end the mission in failure. In three versus three battle phase, the battle is presented in first-person and traditional turn-based battles, player controls one human and two demons, allowing the player to select one action for each squad member, and the computer doing the same for its squad; combat is then resolved after this selection. Players can get their 'Extra Turn' or 'Double Extra' in the battle if the player has attacked the enemy's weaknesses or launched critical attacks, and when a leader's health become zero, the battle ends. Also, the player can crack enemy skills. Once cracked, the player can assign these skills across all of their parties' human characters. In addition to demon fusion, the player can acquire new demons, up to 24 in total, by attempting to win demon auctions using the Macca collected in battle.", stock_info: false, supplier_id: 1, user_id: 1},
  {name: "Uncharted 3", price: "29.99", description: "A search for the fabled Atlantis of the Sands propels fortune hunter Nathan Drake on a trek into the heart of the Arabian Desert. When the terrible secrets of this lost city are unearthed, Drakes quest descends into a desperate bid for survival that strains the limits of his endurance and forces him to confront his deepest fears.", stock_info: false, supplier_id: 2, user_id: 1},
  {name: "Life Is Strange", price: "15.0", description: "Girl falls in love with her best friend as she rewinds time constantly trying to save her best friend from dying. A giant hurricane is coming to destroy the town. Bae over bay!", stock_info: true, supplier_id: 2, user_id: 1},
  {name: "Danganronpa", price: "35.0", description: "Phoenix Wright meets Battle Royale!!!!!!!!", stock_info: true, supplier_id: 2, user_id: 1},
  {name: "Pokemon Alpha Sapphire", price: "17.99", description: "7/10 too much water", stock_info: false, supplier_id: 3, user_id: 1},
  {name: "Mario Kart 8", price: "35.98", description: "Racing with Mario characters.", stock_info: true, supplier_id: 3, user_id: 2},
  {name: "Rayman Legends", price: "20.98", description: "testing 123", stock_info: false, supplier_id: 2, user_id: 2},
  {name: "Animal Crossing: New Leaf", price: "34.99", description: "Become a mayor to your own village!", stock_info: false, supplier_id: 3, user_id: 1},
  {name: "test", price: "34.0", description: "test", stock_info: true, supplier_id: 3, user_id: 1}
])
Supplier.create!([
  {name: "Atlus", email: "persona4ever@atlus.com", phone: 1234567},
  {name: "Sony", email: "sony@playstation.com", phone: 4938456},
  {name: "Nintendo", email: "3ds@nintendo.com", phone: 3333333}
])
